//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanelV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int BlogId { get; set; }
        public string FirstLastName { get; set; }
        public string Email { get; set; }
        public string CommentContent { get; set; }
        public bool Confirmation { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
