//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanelV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminV1 : DbContext
    {
        public AdminV1()
            : base("name=AdminV1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutUs> AboutUs { get; set; }
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<HomeVideo> HomeVideo { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductSliders> ProductSliders { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<SiteIdentity> SiteIdentity { get; set; }
        public virtual DbSet<Sliders> Sliders { get; set; }
        public virtual DbSet<SubCategories> SubCategories { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemAdmin> SystemAdmin { get; set; }
        public virtual DbSet<TablesLogs> TablesLogs { get; set; }
        public virtual DbSet<UserLogs> UserLogs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
