//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanelV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Comments = new HashSet<Comments>();
            this.ProductSliders = new HashSet<ProductSliders>();
        }
    
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public double Price { get; set; }
        public Nullable<double> OldPrice { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Color { get; set; }
        public string File { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> EmendatorAdminId { get; set; }
        public string Tag { get; set; }
        public string ImgUrl { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual SubCategories SubCategories { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSliders> ProductSliders { get; set; }
    }
}
