//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanelV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSliders
    {
        public int SliderId { get; set; }
        public int ProductId { get; set; }
        public string ImgUrl { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
