//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanelV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPasswords
    {
        public int UserId { get; set; }
        public int UserPasswordId { get; set; }
        public string Password { get; set; }
        public string CurrentPassword { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
